"""city fields, event/website archiving, sites.archive permission

Revision ID: 990d6edbb5f9
Revises: 84dd6dda79ec
Create Date: 2026-07-13 15:54:41.310554

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

from app.core.seed import seed_defaults

# revision identifiers, used by Alembic.
revision: str = "990d6edbb5f9"
down_revision: str | None = "84dd6dda79ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_NEW_CODE = "sites.archive"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cities",
        sa.Column("timezone", sa.String(length=64), nullable=False, server_default="UTC"),
    )
    op.add_column("cities", sa.Column("default_latitude", sa.Float(), nullable=True))
    op.add_column("cities", sa.Column("default_longitude", sa.Float(), nullable=True))
    op.add_column("cities", sa.Column("boundary_config", sa.JSON(), nullable=True))
    op.drop_column("cities", "latitude")
    op.drop_column("cities", "longitude")
    op.add_column("events", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("websites", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # --- Data seed: adds the new sites.archive permission + its default-role
    # grants; idempotent, leaves every other permission/role/grant untouched.
    bind = op.get_bind()
    session = Session(bind=bind)
    seed_defaults(session)
    session.close()


def downgrade() -> None:
    bind = op.get_bind()
    session = Session(bind=bind)
    session.execute(
        sa.text(
            "DELETE FROM role_permissions WHERE permission_id IN "
            "(SELECT id FROM permissions WHERE code = :code)"
        ),
        {"code": _NEW_CODE},
    )
    session.execute(sa.text("DELETE FROM permissions WHERE code = :code"), {"code": _NEW_CODE})
    session.commit()
    session.close()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("websites", "archived_at")
    op.drop_column("events", "archived_at")
    op.add_column("cities", sa.Column("longitude", sa.FLOAT(), nullable=True))
    op.add_column("cities", sa.Column("latitude", sa.FLOAT(), nullable=True))
    op.drop_column("cities", "boundary_config")
    op.drop_column("cities", "default_longitude")
    op.drop_column("cities", "default_latitude")
    op.drop_column("cities", "timezone")
    # ### end Alembic commands ###
