"""website onboarding fields

Revision ID: ac034c0f9ec1
Revises: 990d6edbb5f9
Create Date: 2026-07-13 16:21:05.388355

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac034c0f9ec1"
down_revision: str | None = "990d6edbb5f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "websites", sa.Column("source_display_name", sa.String(length=255), nullable=True)
    )
    op.add_column("websites", sa.Column("event_listing_url", sa.String(length=2000), nullable=True))
    op.add_column("websites", sa.Column("timezone_override", sa.String(length=64), nullable=True))
    op.add_column(
        "websites",
        sa.Column(
            "onboarding_status", sa.String(length=32), nullable=False, server_default="draft"
        ),
    )
    op.add_column("websites", sa.Column("proposed_pattern", sa.JSON(), nullable=True))
    op.add_column("websites", sa.Column("approved_pattern", sa.JSON(), nullable=True))
    op.add_column("websites", sa.Column("configuration", sa.JSON(), nullable=True))
    op.add_column("websites", sa.Column("schedule_config", sa.JSON(), nullable=True))
    op.add_column(
        "websites", sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "websites", sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "websites",
        sa.Column("consecutive_failure_count", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("websites", "consecutive_failure_count")
    op.drop_column("websites", "last_failure_at")
    op.drop_column("websites", "last_success_at")
    op.drop_column("websites", "schedule_config")
    op.drop_column("websites", "configuration")
    op.drop_column("websites", "approved_pattern")
    op.drop_column("websites", "proposed_pattern")
    op.drop_column("websites", "onboarding_status")
    op.drop_column("websites", "timezone_override")
    op.drop_column("websites", "event_listing_url")
    op.drop_column("websites", "source_display_name")
    # ### end Alembic commands ###
