"""add auth, sessions, rbac audit fields

Revision ID: 9400754b8944
Revises: 0be6697cdb28
Create Date: 2026-07-13 15:07:42.110865

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

from app.core.permissions import DEFAULT_ROLE_PERMISSIONS
from app.core.seed import seed_defaults

# revision identifiers, used by Alembic.
revision: str = "9400754b8944"
down_revision: str | None = "0be6697cdb28"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("audit_logs", sa.Column("before_state", sa.Text(), nullable=True))
    op.add_column("audit_logs", sa.Column("after_state", sa.Text(), nullable=True))
    op.add_column("audit_logs", sa.Column("correlation_id", sa.String(length=64), nullable=True))
    op.add_column("audit_logs", sa.Column("ip_address", sa.String(length=64), nullable=True))
    op.create_index(
        op.f("ix_audit_logs_correlation_id"), "audit_logs", ["correlation_id"], unique=False
    )
    op.add_column("users", sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # --- Data seed: default roles + permission catalog (idempotent) ---
    bind = op.get_bind()
    session = Session(bind=bind)
    seed_defaults(session)
    session.close()


def downgrade() -> None:
    # Remove only the rows this migration's seed step would have created —
    # leaves any custom roles/permissions added later by admins untouched.
    bind = op.get_bind()
    session = Session(bind=bind)
    session.execute(sa.text("DELETE FROM role_permissions"))
    session.execute(
        sa.text("DELETE FROM roles WHERE name IN :names").bindparams(
            sa.bindparam("names", expanding=True)
        ),
        {"names": list(DEFAULT_ROLE_PERMISSIONS.keys())},
    )
    session.execute(sa.text("DELETE FROM permissions"))
    session.commit()
    session.close()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_login_at")
    op.drop_index(op.f("ix_audit_logs_correlation_id"), table_name="audit_logs")
    op.drop_column("audit_logs", "ip_address")
    op.drop_column("audit_logs", "correlation_id")
    op.drop_column("audit_logs", "after_state")
    op.drop_column("audit_logs", "before_state")
    op.drop_table("user_sessions")
    # ### end Alembic commands ###
